### ISSUE TITLE
Profile needs to be different in case of current user and logged in user

### ISSUE THREAD

**Issue by hassanzhd** [Rubix982/Terrabuzz#154]
Profile currently shows edit in all profiles which should not be the case, edit should only be seen on current user if logged in

### Potential Solution:
Server:
/profile/handle -> [handle]
[handle] == req.userHandle, currentUser: true,
[handle] != req.userHandle, currentUser: false,
(also check if fetched user is connection of user or not and then display connect button)

Client:
[currentUser, .....] <- /profile/handle
currentUser == true, display edit buttons
currentUser == false, display normal profile page

**Comment by Rubix982** [comment]
Closed with #169
