### ISSUE TITLE
Make the navbar render based on if the user is signed in or not

### ISSUE THREAD

**Issue by Rubix982** [Rubix982/Terrabuzz#67]
Add conditional rendering that checks if the user is signed it.

For now, always set the sign in option to true, we will have to deal with this when we talk about authentication.

**Comment by hassanzhd** [comment]
We can now do it @Rubix982, as i have added global loggedIn state to be used

**Comment by Rubix982** [comment]
Acknowledged. We would have to go through each of the pages and substitute for the navbar based on whether the user is logged in or out. 

Some pages will not be rendered to logged out users, for example, /settings.

Seems like a small fix. Assigning this to myself

**Comment by Rubix982** [comment]
Solved with #170
